default:
  image: registry.hzdr.de/multiscale-wdm/surrogate-models/fesl/fesl

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  CONDA_PKGS_DIRS: "${CI_PROJECT_DIR}/conda/pkgs"
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  paths:
    - conda/pkgs
    - .cache/pip
  key: ${CI_JOB_STAGE}

stages:
  - build
  - test
  - deploy

.module_setup: &module_setup
    - cd ../
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.hzdr.de/multiscale-wdm/surrogate-models/fesl/data  fesl_data_repo
    - cd fesl_data_repo
    - git lfs install
    - bash ../fesl/install/data_repo_link/link_data_repo.sh `pwd`
    - cd ../
    - cd fesl
    - conda env create -f install/fesl_cpu_environment.yml
    - source activate fesl-cpu
    - pip install -q -e .


setup-fesl:
  stage: build
  before_script:
    - *module_setup
  script:
    - python examples/ex00_verify_installation.py
  after_script:
      # Remove all untarred directories.
  #  - pwd
  #  - ls -lah
  #  - du -sh conda/pkgs
  #  - find conda/pkgs/ -mindepth 1 -maxdepth 1 -type d -exec rm -r {} \;
  #  - du -sh conda/pkgs
  only:
    - master
    - conda-CI
    - pipelinetest
