default:
  image: registry.hzdr.de/multiscale-wdm/surrogate-models/fesl/fesl

# Change pip's cache and conda's package directories to be inside the project
# directory since we can only cache local items.
variables:
  CONDA_PKGS_DIRS: "${CI_PROJECT_DIR}/conda/pkgs"
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  paths:
    - conda/pkgs
    - .cache/pip
  policy: pull

stages:
  - setup
  - test
  - deploy

.env_setup: &env_setup
  - conda env create -q -f install/fesl_cpu_environment.yml
  - conda clean --tarballs --yes
  - source activate fesl-cpu
  - pip install -q -e .

.data_setup: &data_setup
  - cd ..
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.hzdr.de/multiscale-wdm/surrogate-models/fesl/data  fesl_data_repo
  - cd fesl_data_repo
  - git lfs install
  - bash ../fesl/install/data_repo_link/link_data_repo.sh `pwd`
  - cd ../fesl

setup-fesl:
  stage: setup
  cache:
    paths:
      - conda/pkgs
      - .cache/pip
    policy: pull-push
  before_script:
    - *env_setup
    - *data_setup
  script:
    - python examples/ex00_verify_installation.py

test-basic-functions:
  stage: test
  tags:
    - 2-core
  before_script:
    - *env_setup
    - *data_setup
  script:
    - cd test
    - python fesl_tests.py
  needs: [setup-fesl]

test-workflow:
  stage: test
  before_script:
    - *env_setup
    - *data_setup
  script:
    - cd examples
    - python ex99_verify_all_examples.py
    - cd ..
  needs: [setup-fesl]

#### documentation

setup-docs:
  stage: setup
  image: python:3.7
  cache:
    key: docs-cache
    paths:
      - .cache/pip
  script:
    - pip install -qU pip
    - pip install -qU pydocstyle
    - pip install -qU sphinx
    - pip install -qU sphinx_rtd_theme
    - pip install -qU recommonmark
    - pip install -qU sphinx-markdown-tables

test-docstrings:
  stage: test
  image: python:3.7
  cache:
    key: docs-cache
    paths:
      - .cache/pip
  before_script:
    - pip cache list
    - pip install -qU pip
    - pip install -qU pydocstyle
  script:
    - pydocstyle --convention=numpy fesl
  needs: [setup-docs]

pages:
  stage: deploy
  image: python:3.7
  cache:
    key: docs-cache
    paths:
      - .cache/pip
  before_script:
  - pip cache list
  - pip install -qU pip
  - pip install -qU sphinx
  - pip install -qU sphinx_rtd_theme
  - pip install -qU recommonmark
  - pip install -qU sphinx-markdown-tables
  script:
  - sphinx-apidoc -o docs/source/api fesl
  - sphinx-build -b html -d docs/_build/doctrees docs/source docs/_build/html
  after_script:
  - mv docs/_build/html public
  needs: [test-docstrings]
  artifacts:
    paths:
    - public
  when:
    always
