default:
  image: $CI_REGISTRY_IMAGE:latest

# Change pip's cache and conda's package directories to be inside the project
# directory since we can only cache local items.
variables:
  CONDA_PKGS_DIRS: "${CI_PROJECT_DIR}/conda/pkgs"
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

stages:
  - build
  - setup
  - test
  - deploy

.env_setup: &env_setup
  - pip install -q -e .

.data_setup: &data_setup
  - cd ..
  - git clone -b v0.1.0  https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/hzdr/mala/data  mala_data_repo
  - cd mala_data_repo
  - git lfs install
  - bash ../mala/install/data_repo_link/link_data_repo.sh `pwd`
  - cd ../mala

build-image:
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  tags:
    - docker

setup-mala:
  stage: setup
  before_script:
    - *env_setup
    - *data_setup
  script:
    - python examples/ex00_verify_installation.py

test-basic-functions:
  stage: test
  before_script:
    - *env_setup
    - *data_setup
  script:
    - cd test
    - python mala_tests.py
  needs: [setup-mala]

test-workflow:
  stage: test
  before_script:
    - *env_setup
    - *data_setup
  script:
    - cd examples
    - python ex99_verify_all_examples.py
    - cd ..
  needs: [setup-mala]

#### documentation
setup-docs:
  stage: setup
  image: python:3.7
  cache:
    key: docs-cache
    paths:
      - .cache/pip
  script:
    - pip install -qU pip
    - pip install -qU pydocstyle
    - pip install -qU sphinx
    - pip install -qU sphinx_rtd_theme
    - pip install -qU recommonmark
    - pip install -qU sphinx-markdown-tables

test-docstrings:
  stage: test
  image: python:3.7
  cache:
    key: docs-cache
    paths:
      - .cache/pip
  before_script:
    - pip cache list
    - pip install -qU pip
    - pip install -qU pydocstyle
  script:
    - pydocstyle --convention=numpy mala
  needs: [setup-docs]

pages:
  stage: deploy
  image: python:3.7
  cache:
    key: docs-cache
    paths:
      - .cache/pip
  before_script:
  - pip cache list
  - pip install -qU pip
  - pip install -qU sphinx
  - pip install -qU sphinx_rtd_theme
  - pip install -qU recommonmark
  - pip install -qU sphinx-markdown-tables
  script:
  - sphinx-apidoc -o docs/source/api mala
  - sphinx-build -b html -d docs/_build/doctrees docs/source docs/_build/html
  after_script:
  - mv docs/_build/html public
  needs: [test-docstrings]
  artifacts:
    paths:
    - public
  when:
    always
